[package]
name = "okx-highfrequency"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
arrow = "57.0.0"
chrono = { version = "0.4", features = ["clock"] }
clap = { version = "4.5", features = ["derive"] }
csv = "1.3"
humantime = "2.1"
parquet = { version = "57.0.0", default-features = false, features = ["arrow"] }
